version: 2
updates:
- package-ecosystem: docker
  directory: "/devenv"
  schedule:
    interval: weekly
    time: "06:00"
    timezone: Japan
  open-pull-requests-limit: 10
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: weekly
    time: "06:00"
    timezone: Japan
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "06:00"
    timezone: Japan
  rebase-strategy: disabled
  ignore:
    - dependency-name: "*"
      update-types: ["version-update:semver-patch"]
- package-ecosystem: github-actions
  directory: '/'
  schedule:
    interval: daily
    time: '00:00'
  open-pull-requests-limit: 10
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
  labels:
    - "dependencies"
