version: '3.7'

services:
  web: &web
#    image: cimg/ruby:3.1.0-browsers
    build:
      context: .
      dockerfile: ./devenv/web/Dockerfile
      args:
        IMAGE_FILE: ${IMAGE_FILE:-ruby}
    tmpfs:
      - /tmp
    stdin_open: true
    tty: true
    volumes:
      - .:/work/app:cached
      - rails_cache:/work/app/tmp/cache
      - bundle:/usr/local/bundle
    environment:
      IMAGE_FILE: ${IMAGE_FILE:-ruby}
      BOOTSNAP_CACHE_DIR: '/usr/local/bundle'
      HISTFILE: '/work/app/log/.bash_history'
      TZ: 'Asia/Tokyo'
      RAILS_ENV: ${RAILS_ENV:-development}
      DATABASE_URL: <%= $DATABASE_URL || 'mysql2://root:@db' -%>
      REDIS_URL: ${REDIS_URL:-redis://redis:6379}
      ELASTIC_SEARCH_URL: ${ELASTIC_SEARCH_URL:-http://elasticsearch:9200}
      BUNDLER_VERSION: '2.4.8'
    depends_on:
      - db
      - redis
      - elasticsearch
    command: ["bin/rails", "server", "-b", "0.0.0.0"]
    expose: ["3000"]
    ports:
      - "${WEB_PORT:-53000}:3000"
    working_dir: /work/app
    user: root

  db:
    image: mysql:8.0
    command: ["--bind-address=0.0.0.0"]
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      TZ: Asia/Tokyo
      MYSQL_ROOT_HOST: '%'
    volumes:
      - rails7db:/var/lib/mysql
    ports:
      - "53306:3306"

  rails_cred:
    image: medpeer/rails_cred
    environment:
      RAILS_MASTER_KEY:
    volumes:
    - ./config/credentials:/app/config/credentials:cached

  redis:
    image: "redis:6-alpine"
    ports:
      - "56379:6379"

  chrome:
    build:
      context: .
      dockerfile: ./devenv/chrome/Dockerfile
      args:
        CHROME_IMAGE: ${CHROME_IMAGE:-selenium/standalone-chrome}
      # image: selenium/standalone-chrome:latest
    ports:
      - '4444:4444'

  worker:
    <<: *web
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_URL: redis://redis:6379
    command: bundle exec sidekiq -C config/sidekiq.yml
    ports:
      - "53035:3035"

  elasticsearch:
    build:
      context: .
      dockerfile: ./devenv/elasticsearch/Dockerfile
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    environment:
      http.host: "0.0.0.0"
      http.port: "9200"
      discovery.type: "single-node"
      transport.host: "0.0.0.0"
      network_mode: "host"
      ES_JAVA_OPTS: '-Xms256m -Xmx256m'
      DISABLE_INSTALL_DEMO_CONFIG: true
      node.name: "elasticsearch"
      DISABLE_SECURITY_PLUGIN: true
      xpack.security.enabled: false
      #entrypoint: >
      #  bash -c "bin/elasticsearch-plugin install analysis-kuromoji &&
      #  bin/elasticsearch-plugin install analysis-icu &&
      #  docker-entrypoint.sh"
    expose: [ "9200" ]
    ports:
      - "9200:9200"
    ulimits:
      memlock:
        soft: -1
        hard: -1

volumes:
  bundle:
  rails_cache:
  rails7db:
  elasticsearch:
