version: '3.7'

services:
  web: &web
    # image: circleci/ruby:2.7.2-node-browsers
    build:
      context: .
      dockerfile: ./devenv/web/Dockerfile
    tmpfs:
      - /tmp
    stdin_open: true
    tty: true
    volumes:
      - .:/app:cached
      - rails_cache:/app/tmp/cache
      - bundle:/usr/local/bundle
    environment:
      BOOTSNAP_CACHE_DIR: '/usr/local/bundle'
      HISTFILE: '/app/log/.bash_history'
      TZ: 'Asia/Tokyo'
      RAILS_ENV: ${RAILS_ENV:-development}
      DATABASE_URL: 'mysql2://root:@db'
      REDIS_URL: redis://redis:6379
      ELASTICSEARCH_URL: http://elasticsearch:9200
    depends_on:
      - db
      - redis
      - elasticsearch
    command: ["bin/rails", "server", "-b", "0.0.0.0"]
    expose: ["3000"]
    ports:
      - "${WEB_PORT:-53000}:3000"
    working_dir: /app
    user: root

  db:
    image: mysql:5.7
    command: ["--bind-address=0.0.0.0"]
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      TZ: Asia/Tokyo
    volumes:
      - db:/var/lib/mysql
    ports:
      - "53306:3306"

  rails_cred:
    image: medpeer/rails_cred
    environment:
      RAILS_MASTER_KEY:
    volumes:
      - ./config/credentials:/app/config/credentials:cached

  redis:
    image: "redis:6-alpine"
    ports:
      - "56379:6379"

  worker:
    <<: *web
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_URL: redis://redis:6379
    command: bundle exec sidekiq -C config/sidekiq.yml
    ports:
      - "53035:3035"

  elasticsearch:
    build:
      context: .
      dockerfile: ./devenv/elasticsearch/Dockerfile
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    environment:
      http.host: "0.0.0.0"
      http.port: "9200"
      discovery.type: "single-node"
      ES_JAVA_OPTS: '-Xms256m -Xmx256m'
      #entrypoint: >
      #  bash -c "bin/elasticsearch-plugin install analysis-kuromoji &&
      #  bin/elasticsearch-plugin install analysis-icu &&
      #  docker-entrypoint.sh"
    expose: [ "9200" ]

volumes:
  bundle:
  rails_cache:
  db:
  elasticsearch:
