default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV['DATABASE_URL'] %>

development:
  <<: *default
  database: rails6_development
  host: db

test:
  <<: *default
  database: rails6_test

production:
  <<: *default
  encoding: utf8mb4
  database: rails6
