name: Build

#プルリクエスト作成時に実行(他にもpush時など設定できます)
on:
  pull_request:
    types: [opened, reopened, synchronize]

concurrency:
  group: rails7-${{ github.event.pull_request.head.ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  rspec-job:
    #ubuntu環境で動かします
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      RAILS_ENV: test

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
      elasticsearch:
        image: elasticsearch:7.17.9
        ports:
          - 9200/tcp
        options: -e="discovery.type=single-node" --health-cmd="curl http://localhost:9200/_cluster/health" --health-interval=10s --health-timeout=5s --health-retries=10
#      chrome:
#        image: selenium/standalone-chrome
#        ports:
#          - 4444:4444
#          - 5900:5900

    # https://github.com/ruby/setup-ruby
    steps:
      - name: checkout
        if: ${{ github.event_name != 'pull_request' }}
        uses: actions/checkout@v3
      - name: checkout pr
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Setup Ruby version
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.1
          bundler-cache: true
      - name: Use Node.js 16.19.0
        uses: actions/setup-node@v3
        with:
          node-version: 16.19.0
      # elasticsearch起動用に必要
      - name: Configure sysctl limits
        run: |
          sudo swapoff -a
          sudo sysctl -w vm.swappiness=1
          sudo sysctl -w fs.file-max=262144
          sudo sysctl -w vm.max_map_count=262144
      - name: Run Elasticsearch
        uses: perfect-ruby-on-rails/elasticsearch-with-plugins-action@v1
        with:
          stack-version: 7.17.9
          plugins: |
            analysis-kuromoji
            analysis-icu
      #MySQLをインストール
      - name: Install dependent libralies
        run: sudo apt-get update -y && sudo apt-get install libmysqlclient-dev
      - name: Verify Elasticsearch connection from host
        env:
          ELASTIC_SEARCH_URL: http://127.0.0.1:${{ job.services.elasticsearch.ports[9200] }}
        run: |
          echo $ELASTIC_SEARCH_URL
          curl -fsSL "$ELASTIC_SEARCH_URL/_cat/health?h=status"
      - name: check elastic-search plugin
        run: |
          curl -X GET "$ELASTIC_SEARCH_URL/_nodes/plugins?pretty"

      - name: Setup bundler
        run: gem install bundler

      - name: bundle install
        run: |
          bundle config set path 'vendor/bundle'
          bundle install --jobs 4 --retry 3
      - name: yarn install
        run: yarn install --check-files

      - name: Setup Database
        run: |
          cp config/database.yml.github-actions config/database.yml
          bundle exec rake db:create
          bundle exec rake db:migrate
          # bundle exec rake db:schema:load

      - name: Run Brakeman
        run: bundle exec brakeman

      - name: Run RSpec
        run: |
          bundle exec rails r "Event.reindex"
          bundle exec rspec
        env:
          ELASTIC_SEARCH_URL: http://127.0.0.1:${{ job.services.elasticsearch.ports[9200] }}
      - name: Codecov
        uses: codecov/codecov-action@v2.1.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: coverage # このディレクトリに、テスティングツールによるカバレッジレポートファイルが出力される想定
